version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: cinemax-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  redis:
    image: redis:7-alpine
    container_name: cinemax-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cinemax-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/movie-reservation?authSource=admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URL: http://localhost:5173
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./server/uploads:/app/uploads

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinemax-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend

volumes:
  mongodb_data:
  redis_data: